#cloud-config
# users:
#   - default
#   - name: bluedata
#     groups: [sudo, wheel]
#     shell: /bin/bash
#     sudo: ['ALL=(ALL) NOPASSWD:ALL']
#     ssh-authorized-keys: 
#       - PUB_KEY

package_upgrade: true
# runcmd:
#   - sudo yum install -y python-pip
#   - sudo yum install -y python-setuptools
#   - pip install --upgrade pip
#   - pip install --upgrade setuptools

# packages:
#   - epel-release
repo_update: true
repo_upgrade: all
runcmd:
#   - sudo sed -i --follow-symlinks 's/^SELINUX=.*/SELINUX=disabled/g' /etc/sysconfig/selinux
  # // run fastdd in background session.  nohup and disown both failed to achieve this over ssh.
  - "sudo tmux new-session -d -s mySession -n myWindow && sudo tmux send-keys -t mySession:myWindow \"fastdd\" Enter",
  - "sudo sed -i 's/1/0/g' /etc/apt/apt.conf.d/20auto-upgrades",
  - "sudo apt -qq update",
  - "sudo apt -qq install -y firefox",
  - "sudo snap install gedit",
  - "curl -LO https://storage.googleapis.com/kubernetes-release/release/`curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt`/bin/linux/amd64/kubectl",
  - "chmod +x ./kubectl",
  - "sudo mv ./kubectl /usr/local/bin/kubectl",
  - "echo 'source <(kubectl completion bash)' >>~/.bashrc",
  - "sudo bash -c 'kubectl completion bash >/etc/bash_completion.d/kubectl'",
  - "echo 'alias k=kubectl' >>~/.bashrc",
  - "echo 'complete -F __start_kubectl k' >>~/.bashrc",
  - "curl -L0 https://releases.hashicorp.com/terraform/0.12.24/terraform_0.12.24_linux_amd64.zip > terraform_0.12.24_linux_amd64.zip",
  - "unzip terraform_0.12.24_linux_amd64.zip",
  - "chmod a+x terraform",
  - "sudo mv terraform /usr/local/bin/",
  - "rm terraform_0.12.24_linux_amd64.zip",
  - "mkdir /home/ubuntu/Desktop",
  - "sudo -H pip3 install hpecp",
  - "echo 'source <(hpecp autocomplete bash)' >>~/.bashrc"

# disk_setup:
#   ephemeral0:
#     table_type: gpt
#     layout: [[100,82]]
#     overwrite: true
# fs_setup:
#   - device: ephemeral0.1
#     filesystem: swap
# mounts:
#   - ["ephemeral0.1", "none", "swap", "sw", "0", "0"]

# power_state:
#   mode: reboot